### ISSUE TITLE
Information de l'avancé du process 

### ISSUE THREAD

**Issue by operon** [panoramax-project/DetectionTutorial#10]
Dans predict,
Afin de pouvoir anticiper et se rendre compte du temps du process, ça serait bien de pouvoir avoir une information de l'avancé.

- Dès le début compter le nombre de séquences qui seront analysées dans la bbox
- A chaque séquence analysée "print("  - Find pictures in sequence"**_, x/Nbr, xx%_** , collection["id"])

**Comment by PanierAvide** [comment]
Implémenté, merci pour l'idée :+1:

**Comment by operon** [comment]
Bizarre, que ce soit sur l'instance Openstreetmap ou Metacatalogue, 100 séquences de trouvées dans une bbox département Vendée, alors que je pense qu'il y en a plus. Une limite dans le code ?
nbSequences = len(pnmxCollections["collections"])

Selon l'instance pour une même séquence, pas le même nombre de d'images trouvées ?
![image](https://github.com/panoramax-project/DetectionTutorial/assets/7881707/0176ebd0-c9f3-4684-a98a-88616ed6e215)

**Comment by PanierAvide** [comment]
C'est plus la non-gestion de la pagination, comme il y a beaucoup plus de séquences que ça, l'API renvoie un lien suivant à récupérer pour avoir la suite... Je vais rajouter ça.

**Comment by PanierAvide** [comment]
Implémenté dans https://github.com/panoramax-project/DetectionTutorial/commit/7ab0fe8d7cf96d9eb1d35e320dde457498853393
