### ISSUE TITLE
Plusieurs class à chercher

### ISSUE THREAD

**Issue by operon** [panoramax-project/DetectionTutorial#3]
Bonjour,

Je cherche à utiliser ce fichier (predict_pano.py) pour trouver plusieurs instances de panneaux qui sont dans le même fichier d’entrainement sous plusieurs class différentes.

Il faut lancer plusieurs fois le script en modifiant : 
# Class ID to target in detections
CLASS_ID=0
# Object name (only for display)
OBJECT_NAME="Hydrant"

ou il est possible de modifier le fichier pour boucler sur plusieurs class ?
Dans ce cas, je patienterais car je ne serais pas proposer une modif.

Merci

**Comment by PanierAvide** [comment]
Le plus simple va être de modifier la ligne 40 de `predict_pano.py` en :

```python
	results = model.predict(source=chunk, imgsz=2048, stream=True, classes=[1,2,3], verbose=False)
```

Donc retirer le `max_det=1`, et mettre dans `classes=[...]` la liste des classes que tu recherches (les IDs commencent à 0 par rapport au fichier classes.txt).
