### ISSUE TITLE
Paramétre imgsz=640

### ISSUE THREAD

**Issue by operon** [panoramax-project/DetectionTutorial#4]
Dans le code de predict_pano.py il est indiqué " imgsz=640"

A quoi ça correspond et ce paramètre ne devrait pas il être dans une variable au début du fichier ?

```
chunk = picturesUrls[start:end]
results = model.predict(source=chunk, imgsz=640, stream=True, max_det=1, classes=[CLASS_ID], verbose=False)
i = 0
```

**Comment by PanierAvide** [comment]
Ça a été corrigé entre temps, voir https://github.com/panoramax-project/DetectionTutorial/blob/main/predict_pano.py#L40

N'hésite pas à récupérer la dernière version du dépôt pour être sûr :wink:
