### ISSUE TITLE
predict_pano : Save results outputGeojson

### ISSUE THREAD

**Issue by operon** [panoramax-project/DetectionTutorial#8]
Bonjour,

Je n'ai pas compris à quel moment est compléter le dossier "OUTPUT_GEOJSON",soit en cours d'analyse soir à la fin du traitement.

De plus, je ne vois pas de partie "Create output directory" dans "Save results" comme dans "Checking collections one by one"

Cordialement

**Comment by PanierAvide** [comment]
`OUTPUT_GEOJSON` est un fichier (pas un dossier), créé à la toute fin de l'exécution du script, une fois qu'on a toutes les positions des objets détectés stockées. On est obligé de le faire en dernier vu que c'est du GeoJSON, qu'on peut difficilement écrire au fur et à mesure.
