### ISSUE TITLE
predict_pano.py : SEARCH_BBOX

### ISSUE THREAD

**Issue by operon** [panoramax-project/DetectionTutorial#9]
Dans predict_pano.py, j'ai mis `SEARCH_BBOX=[-1.3373961,46.7013888,-1.323309,46.7014]` et j'utilise `PANORAMAX_API="https://panoramax.openstreetmap.fr/api"`
C'est une bbox très restreinte dans laquelle il ne devrait y avoir qu'une dizaine de séquences.

Lorsque je lance le script les images ds séquences qui ne traversent pas cette bbox sont utilisées.
[https://panoramax.openstreetmap.fr/api/collections?bbox=-1.3373961,46.7013888,-1.323309,46.7014](https://panoramax.openstreetmap.fr/api/collections?bbox=-1.3373961,46.7013888,-1.323309,46.7014)

**Comment by PanierAvide** [comment]
Je viens de modifier le script en conséquence, seules les photos dans la zone seront conservées
